### PR TITLE
Circle CI config

### PR DESCRIPTION
**Pull request by khanhicetea**
Need to set 2 env variables in Circle CI : 
- `EXPO_USERNAME`
- `EXPO_PASSWORD`

Notice :
- *In case you signin Expo via Github, try to logout then forgot password 😸  *
- Remove `|| true` after fixing TSC error

### CODE REVIEW

**Comment by khanhicetea** [comment]
Try to resolve #4

**Comment by her0e1c1** [comment]
@khanhicetea thanks! I will set up now

**Comment by khanhicetea** [comment]
Ok, let me know if something went wrong :)

----------------
Khanh, Nguyen

**Comment by her0e1c1** [comment]
ya thanks! I set the two envs. btw I'm a bit afraid that logging show env vars :(

**Comment by khanhicetea** [comment]
So use useless password or random password. B/c expo isn't important service to use real password ;)

----------------
Khanh, Nguyen

**Comment by her0e1c1** [comment]
oh ok :)

**Pull request merged**
